import { test, expect } from '@playwright/test';

test('shows graph context after relation intent flow', async ({ page, request }) => {
  test.setTimeout(600_000);
  const sessionId = `ui${Date.now()}`;
  const postTurn = async (intent) => {
    const resp = await request.post('/api/turn', { data: { sessionId, intent } });
    expect(resp.ok()).toBeTruthy();
  };

  const init = await request.post('/api/session/init', { data: { sessionId } });
  expect(init.ok()).toBeTruthy();
  await postTurn('add task ui graph trace');
  await postTurn('add note relation target');
  await postTurn('link task 1 references note 1');
  await postTurn('add task dependency mid');
  await postTurn('add task dependency leaf');
  const graphResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph?limit=200`);
  expect(graphResp.ok()).toBeTruthy();
  const graphPayload = await graphResp.json();
  const entities = Array.isArray(graphPayload.entities) ? graphPayload.entities : [];
  const rootTask = entities.find((e) => String(e.kind || '').toLowerCase() === 'task' && String(e.title || '') === 'ui graph trace');
  const midTask = entities.find((e) => String(e.kind || '').toLowerCase() === 'task' && String(e.title || '') === 'dependency mid');
  const leafTask = entities.find((e) => String(e.kind || '').toLowerCase() === 'task' && String(e.title || '') === 'dependency leaf');
  expect(rootTask).toBeTruthy();
  expect(midTask).toBeTruthy();
  expect(leafTask).toBeTruthy();
  await postTurn(`link task ${String(rootTask.id).slice(0, 8)} depends_on task ${String(midTask.id).slice(0, 8)}`);
  await postTurn(`link task ${String(midTask.id).slice(0, 8)} depends_on task ${String(leafTask.id).slice(0, 8)}`);
  const graphSchemaResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/schema`);
  expect(graphSchemaResp.ok()).toBeTruthy();
  const graphQueryResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/query?kind=task&limit=5`);
  expect(graphQueryResp.ok()).toBeTruthy();
  const graphNeighborhoodResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/neighborhood?kind=task&selector=${encodeURIComponent(String(rootTask.id).slice(0, 8))}&depth=2`);
  expect(graphNeighborhoodResp.ok()).toBeTruthy();
  const graphPathResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/path?source_kind=task&source=${encodeURIComponent(String(rootTask.id).slice(0, 8))}&target_kind=task&target=${encodeURIComponent(String(leafTask.id).slice(0, 8))}&relation=depends_on&directed=true`);
  expect(graphPathResp.ok()).toBeTruthy();
  const graphHealthResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/health`);
  expect(graphHealthResp.ok()).toBeTruthy();
  const graphComponentsResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/components?relation=depends_on&limit=10`);
  expect(graphComponentsResp.ok()).toBeTruthy();
  const graphHubsResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/hubs?relation=depends_on&limit=10`);
  expect(graphHubsResp.ok()).toBeTruthy();
  const graphEventsResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/events?limit=20`);
  expect(graphEventsResp.ok()).toBeTruthy();
  const graphSummaryResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/summary?relation=depends_on&limit=10`);
  expect(graphSummaryResp.ok()).toBeTruthy();
  const graphRelationMatrixResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/relation-matrix?relation=depends_on&limit=100`);
  expect(graphRelationMatrixResp.ok()).toBeTruthy();
  const graphAnomaliesResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/anomalies?limit=20`);
  expect(graphAnomaliesResp.ok()).toBeTruthy();
  const graphGuidanceResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/guidance?limit=8`);
  expect(graphGuidanceResp.ok()).toBeTruthy();
  const graphScoreResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score`);
  expect(graphScoreResp.ok()).toBeTruthy();
  const graphScoreTrendResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-trend?window_ms=3600000&buckets=8`);
  expect(graphScoreTrendResp.ok()).toBeTruthy();
  const graphScoreGuidanceResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-guidance?limit=6`);
  expect(graphScoreGuidanceResp.ok()).toBeTruthy();
  const graphScoreAlertsResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-alerts?limit=10`);
  expect(graphScoreAlertsResp.ok()).toBeTruthy();
  const graphScoreAlertsHistoryResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-alerts-history?window_ms=3600000&buckets=8&limit=5`);
  expect(graphScoreAlertsHistoryResp.ok()).toBeTruthy();
  const graphScoreRemediationResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-remediation?limit=6`);
  expect(graphScoreRemediationResp.ok()).toBeTruthy();
  const graphScoreForecastResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-forecast?horizon_ms=3600000&step_buckets=6`);
  expect(graphScoreForecastResp.ok()).toBeTruthy();
  const graphScoreForecastGuidanceResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-forecast-guidance?limit=6`);
  expect(graphScoreForecastGuidanceResp.ok()).toBeTruthy();
  const graphScoreGuardrailsResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-guardrails?warn_below=75&fail_below=60`);
  expect(graphScoreGuardrailsResp.ok()).toBeTruthy();
  const graphScoreAutopilotPreviewResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot-preview?limit=6`);
  expect(graphScoreAutopilotPreviewResp.ok()).toBeTruthy();
  const graphScoreAutopilotRunResp = await request.post(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/run`, { data: { mode: 'dry_run', limit: 6 } });
  expect(graphScoreAutopilotRunResp.ok()).toBeTruthy();
  const graphScoreAutopilotHistoryResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/history?limit=20`);
  expect(graphScoreAutopilotHistoryResp.ok()).toBeTruthy();
  const graphScoreAutopilotMetricsResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/metrics?window_ms=86400000`);
  expect(graphScoreAutopilotMetricsResp.ok()).toBeTruthy();
  const graphScoreAutopilotAnomaliesResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/anomalies?window_ms=86400000&limit=10`);
  expect(graphScoreAutopilotAnomaliesResp.ok()).toBeTruthy();
  const graphScoreAutopilotGuidanceResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/guidance?window_ms=86400000&limit=8`);
  expect(graphScoreAutopilotGuidanceResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy?window_ms=86400000`);
  expect(graphScoreAutopilotPolicyResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyDriftResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-drift?window_ms=86400000`);
  expect(graphScoreAutopilotPolicyDriftResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentActionsResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-actions?window_ms=86400000&limit=6`);
  expect(graphScoreAutopilotPolicyAlignmentActionsResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentRunResp = await request.post(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-run`, { data: { mode: 'dry_run', windowMs: 86400000, limit: 6 } });
  expect(graphScoreAutopilotPolicyAlignmentRunResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentHistoryResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-history?limit=20`);
  expect(graphScoreAutopilotPolicyAlignmentHistoryResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentMetricsResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-metrics?window_ms=86400000`);
  expect(graphScoreAutopilotPolicyAlignmentMetricsResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentAnomaliesResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-anomalies?window_ms=86400000&limit=10`);
  expect(graphScoreAutopilotPolicyAlignmentAnomaliesResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentGuidanceResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-guidance?window_ms=86400000&limit=8`);
  expect(graphScoreAutopilotPolicyAlignmentGuidanceResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy?window_ms=86400000`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyDriftResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-drift?window_ms=86400000`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyDriftResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyGuidanceResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-guidance?window_ms=86400000&limit=8`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyGuidanceResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyRunResp = await request.post(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-run`, { data: { mode: 'dry_run', windowMs: 86400000, limit: 8 } });
  expect(graphScoreAutopilotPolicyAlignmentPolicyRunResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyHistoryResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-history?limit=20`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyHistoryResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyMetricsResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-metrics?window_ms=86400000`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyMetricsResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyAnomaliesResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-anomalies?window_ms=86400000&limit=10`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyAnomaliesResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicySummaryResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-summary?window_ms=86400000&limit=8`);
  expect(graphScoreAutopilotPolicyAlignmentPolicySummaryResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend?window_ms=86400000`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidanceResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance?window_ms=86400000&limit=6`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidanceResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidanceRunResp = await request.post(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-run`, { data: { mode: 'dry_run', windowMs: 86400000, limit: 6 } });
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidanceRunResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidanceHistoryResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-history?limit=20`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidanceHistoryResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidanceMetricsResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-metrics?window_ms=86400000`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidanceMetricsResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidanceAnomaliesResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-anomalies?window_ms=86400000&limit=10`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidanceAnomaliesResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidanceSummaryResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-summary?window_ms=86400000&limit=8`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidanceSummaryResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy?window_ms=86400000`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyDriftResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-drift?window_ms=86400000`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyDriftResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance?window_ms=86400000&limit=8`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceRunResp = await request.post(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-run`, { data: { mode: 'dry_run', windowMs: 86400000, limit: 8 } });
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceRunResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceHistoryResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-history?limit=20`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceHistoryResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceMetricsResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-metrics?window_ms=86400000`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceMetricsResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceAnomaliesResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-anomalies?window_ms=86400000&limit=10`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceAnomaliesResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceSummaryResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-summary?window_ms=86400000&limit=8`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceSummaryResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state?window_ms=86400000`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateMetricsResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-metrics?window_ms=86400000`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateMetricsResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateAnomaliesResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-anomalies?window_ms=86400000&limit=10`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateAnomaliesResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateSummaryResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-summary?window_ms=86400000&limit=8`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateSummaryResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance?window_ms=86400000&limit=8`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceRunResp = await request.post(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-run`, { data: { mode: 'dry_run', windowMs: 86400000, limit: 8 } });
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceRunResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceHistoryResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-history?limit=20`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceHistoryResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceMetricsResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-metrics?window_ms=86400000`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceMetricsResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceAnomaliesResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-anomalies?window_ms=86400000&limit=10`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceAnomaliesResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceSummaryResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-summary?window_ms=86400000&limit=8`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceSummaryResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state?window_ms=86400000`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateTrendResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-trend?window_ms=86400000`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateTrendResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateOffendersResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-offenders?window_ms=86400000&limit=8`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateOffendersResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateTimelineResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-timeline?window_ms=86400000&limit=20`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateTimelineResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateMatrixResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-matrix?window_ms=86400000`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateMatrixResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-guidance?window_ms=86400000&limit=8`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceRunResp = await request.post(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-guidance-run`, { data: { mode: 'dry_run', windowMs: 86400000, limit: 8 } });
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceRunResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceHistoryResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-guidance-history?limit=20`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceHistoryResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceMetricsResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-guidance-metrics?window_ms=86400000`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceMetricsResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceAnomaliesResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-guidance-anomalies?window_ms=86400000&limit=10`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceAnomaliesResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceSummaryResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-guidance-summary?window_ms=86400000&limit=8`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceSummaryResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-guidance-state?window_ms=86400000`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateHistoryResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-guidance-state-history?limit=20`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateHistoryResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateMetricsResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-guidance-state-metrics?window_ms=86400000`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateMetricsResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateAnomaliesResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-guidance-state-anomalies?window_ms=86400000&limit=10`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateAnomaliesResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateSummaryResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-guidance-state-summary?window_ms=86400000&limit=8`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateSummaryResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunResp = await request.post(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-guidance-state-run`, { data: { mode: 'dry_run', windowMs: 86400000, limit: 8 } });
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunHistoryResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-guidance-state-run-history?limit=20`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunHistoryResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunMetricsResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-guidance-state-run-metrics?window_ms=86400000`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunMetricsResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunAnomaliesResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-guidance-state-run-anomalies?window_ms=86400000&limit=10`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunAnomaliesResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunSummaryResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-guidance-state-run-summary?window_ms=86400000&limit=8`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunSummaryResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunStateResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-guidance-state-run-state?window_ms=86400000`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunStateResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunStateHistoryResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-guidance-state-run-state-history?limit=20`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunStateHistoryResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunStateMetricsResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-guidance-state-run-state-metrics?window_ms=86400000`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunStateMetricsResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunStateAnomaliesResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-guidance-state-run-state-anomalies?window_ms=86400000&limit=10`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunStateAnomaliesResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunStateSummaryResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-guidance-state-run-state-summary?window_ms=86400000&limit=8`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunStateSummaryResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunStateGuidanceResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-guidance-state-run-state-guidance?window_ms=86400000&limit=8`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunStateGuidanceResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunStateGuidanceRunResp = await request.post(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-guidance-state-run-state-guidance-run`, { data: { mode: 'dry_run', windowMs: 86400000, limit: 8 } });
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunStateGuidanceRunResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunStateGuidanceRunHistoryResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-guidance-state-run-state-guidance-run-history?limit=20`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunStateGuidanceRunHistoryResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunStateGuidanceRunMetricsResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-guidance-state-run-state-guidance-run-metrics?window_ms=86400000`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunStateGuidanceRunMetricsResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunStateGuidanceRunAnomaliesResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-guidance-state-guidance-state-run-state-guidance-run-anomalies?window_ms=86400000&limit=10`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateGuidanceStateGuidanceStateRunStateGuidanceRunAnomaliesResp.ok()).toBeTruthy();
  const graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateHistoryResp = await request.get(`/api/session/${encodeURIComponent(sessionId)}/graph/score-autopilot/policy-alignment-policy-trend-guidance-policy-guidance-state-history?limit=20`);
  expect(graphScoreAutopilotPolicyAlignmentPolicyTrendGuidancePolicyGuidanceStateHistoryResp.ok()).toBeTruthy();

  await page.goto(`/?session=${sessionId}`);

  const input = page.locator('#intent-input');
  await expect(input).toBeVisible();
  await input.click();

  const submitIntent = async (text) => {
    const resp = await page.request.post('/api/turn', {
      data: { sessionId, intent: text, onConflict: 'merge' },
      timeout: 60_000,
    });
    expect(resp.ok()).toBeTruthy();
  };

  await submitIntent('show references for note 1');
  await submitIntent('show graph schema');
  await submitIntent('show graph health');
  await submitIntent('show graph components relation depends_on limit 10');
  await submitIntent('show graph hubs relation depends_on limit 10');
  await submitIntent('show graph events limit 20');
  await submitIntent('show graph summary relation depends_on limit 10');
  await submitIntent('show graph relation matrix relation depends_on limit 100');
  await submitIntent('show graph anomalies limit 20');
  await submitIntent('show graph guidance limit 8');
  await submitIntent('show graph score');
  await submitIntent('show graph score trend window 1h buckets 8');
  await submitIntent('show graph score guidance limit 6');
  await submitIntent('show graph score alerts limit 10');
  await submitIntent('show graph score alerts history window 1h buckets 8 limit 5');
  await submitIntent('show graph score remediation limit 6');
  await submitIntent('show graph score forecast horizon 1h steps 6');
  await submitIntent('show graph score forecast guidance limit 6');
  await submitIntent('show graph score guardrails warn below 75 fail below 60');
  await submitIntent('show graph score autopilot preview limit 6');
  await submitIntent('run graph score autopilot dry run limit 6');
  await submitIntent('show graph score autopilot history limit 20');
  await submitIntent('show graph score autopilot metrics window 24h');
  await submitIntent('show graph score autopilot anomalies window 24h limit 10');
  await submitIntent('show graph score autopilot guidance window 24h limit 8');
  await submitIntent('show graph score autopilot policy window 24h');
  await submitIntent('show graph score autopilot policy drift window 24h');
  await submitIntent('show graph score autopilot policy alignment actions window 24h limit 6');
  await submitIntent('run graph score autopilot policy alignment dry run window 24h limit 6');
  await submitIntent('show graph score autopilot policy alignment history limit 20');
  await submitIntent('show graph score autopilot policy alignment metrics window 24h');
  await submitIntent('show graph score autopilot policy alignment anomalies window 24h limit 10');
  await submitIntent('show graph score autopilot policy alignment guidance window 24h limit 8');
  await submitIntent('show graph score autopilot policy alignment policy window 24h');
  await submitIntent('show graph score autopilot policy alignment policy drift window 24h');
  await submitIntent('show graph score autopilot policy alignment policy guidance window 24h limit 8');
  await submitIntent('run graph score autopilot policy alignment policy dry run window 24h limit 8');
  await submitIntent('show graph score autopilot policy alignment policy history limit 20');
  await submitIntent('show graph score autopilot policy alignment policy metrics window 24h');
  await submitIntent('show graph score autopilot policy alignment policy anomalies window 24h limit 10');
  await submitIntent('show graph score autopilot policy alignment policy summary window 24h limit 8');
  await submitIntent('show graph score autopilot policy alignment policy trend window 24h');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance window 24h limit 6');
  await submitIntent('run graph score autopilot policy alignment policy trend guidance dry run window 24h limit 6');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance history limit 20');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance metrics window 24h');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance anomalies window 24h limit 10');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance summary window 24h limit 8');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy window 24h');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy drift window 24h');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance window 24h limit 8');
  await submitIntent('run graph score autopilot policy alignment policy trend guidance policy guidance dry run window 24h limit 8');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance history limit 20');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance metrics window 24h');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance anomalies window 24h limit 10');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance summary window 24h limit 8');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state window 24h');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state metrics window 24h');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state anomalies window 24h limit 10');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state summary window 24h limit 8');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance window 24h limit 8');
  await submitIntent('run graph score autopilot policy alignment policy trend guidance policy guidance state guidance dry run window 24h limit 8');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance history limit 20');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance metrics window 24h');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance anomalies window 24h limit 10');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance summary window 24h limit 8');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance state window 24h');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance state trend window 24h');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance state offenders window 24h limit 8');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance state timeline window 24h limit 20');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance state matrix window 24h');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance state guidance window 24h limit 8');
  await submitIntent('run graph score autopilot policy alignment policy trend guidance policy guidance state guidance state guidance dry run window 24h limit 8');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance state guidance history limit 20');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance state guidance metrics window 24h');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance state guidance anomalies window 24h limit 10');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance state guidance summary window 24h limit 8');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance state guidance state window 24h');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance state guidance state history limit 20');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance state guidance state metrics window 24h');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance state guidance state anomalies window 24h limit 10');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance state guidance state summary window 24h limit 8');
  await submitIntent('run graph score autopilot policy alignment policy trend guidance policy guidance state guidance state guidance state dry run window 24h limit 8');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance state guidance state run history limit 20');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance state guidance state run metrics window 24h');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance state guidance state run anomalies window 24h limit 10');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance state guidance state run summary window 24h limit 8');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance state guidance state run state window 24h');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance state guidance state run state history limit 20');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance state guidance state run state metrics window 24h');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance state guidance state run state anomalies window 24h limit 10');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance state guidance state run state summary window 24h limit 8');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance state guidance state run state guidance window 24h limit 8');
  await submitIntent('run graph score autopilot policy alignment policy trend guidance policy guidance state guidance state guidance state run state guidance dry run window 24h limit 8');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance state guidance state run state guidance run history limit 20');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance state guidance state run state guidance run metrics window 24h');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state guidance state guidance state run state guidance run anomalies window 24h limit 10');
  await submitIntent('show graph score autopilot policy alignment policy trend guidance policy guidance state history limit 20');
  await submitIntent('show graph kind task limit 5');
  await submitIntent(`show graph neighborhood for task ${String(rootTask.id).slice(0, 8)} depth 2`);
  await submitIntent(`show graph path task ${String(rootTask.id).slice(0, 8)} to task ${String(leafTask.id).slice(0, 8)} relation depends_on directed on`);
  await submitIntent(`show dependency chain for task ${String(rootTask.id).slice(0, 8)}`);
  await submitIntent(`show blockers for task ${String(rootTask.id).slice(0, 8)}`);
  await submitIntent(`show impact for task ${String(leafTask.id).slice(0, 8)}`);

  await expect(page.getByText('Graph Context')).toBeVisible();
  await expect(page.getByText(/relations:\s*[1-9]/i)).toBeVisible();
  const relationKindSignal = page.getByText(/(references|depends_on):\s*[1-9]/i);
  await expect(relationKindSignal.first()).toBeVisible();
});
